name: peter_tok
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pillow
  - ffmpeg
  - pip:
    - moviepy
    - pydub
    - vosk
    - stable-whisper
    - wave
    - contextlib
    - regex
    - tempfile