name: peter_tok
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pillow
  - ffmpeg
  - pip:
    - moviepy
    - pydub
    - vosk
    - stable-ts
    - wave
    - regex
    - mistralai
    - git+https://github.com/fishaudio/fish-audio-python.git
    - python-dotenv